---
language: objective-c

os:
  - osx

osx_image: xcode7

script:
  - curl -s https://raw.githubusercontent.com/superlumic/superlumic/master/superlumic | bash -s https://github.com/sundeer/superlumic-config.git
