---

- name: Register current git user.name
  shell: git config --global --get user.name
  register: current_git_user_name
  changed_when: False
  ignore_errors: yes

- name: Register current git user.email
  shell: git config --global --get user.email
  register: current_git_user_email
  changed_when: False
  ignore_errors: yes

- name: Set git user.name
  shell: git config --global user.name {{git.user_name}}
  when: "{{ git.user_name }} != {{current.git.user_name}}"

- name: Set git user.email
  shell: git config --global user.email "{{git.user_email}}"
  when: git_user_email_result.stdout != "{{git.user_email}}"
  when: "{{ git.user_name }} != {{current_git.user_name}}"
