---

- name: Register current git user.name
  shell: git config --global --get user.name
  register: current_git_user_name
  changed_when: False
  ignore_errors: yes

- name: Register current git user.email
  shell: git config --global --get user.email
  register: current_git_user_email
  changed_when: False
  ignore_errors: yes

- name: Set git user.name
  shell: git config --global user.name {{git.user_name}}
  when: current_git_user_name.stdout != {{current_git_user_name}}

- name: Set git user.email
  shell: git config --global user.email {{git.user_email}}
  when: current_git_user_email.stdout != {{git.user_email}}
