---

- name: Set ComputerName to {{ system_name }}
  command: scutil --set ComputerName {{ system_name }}
  become: yes
  when: ansible_hostname != system_name

- name: Set HostName to {{ system_name }}
  command: scutil --set HostName {{ system_name }}
  become: yes
  when: ansible_hostname != system_name

- name: Set LocalHostName to {{ system_name }}
  command: scutil --set LocalHostName {{ system_name }}
  sudo: yes
  when: ansible_hostname != system_name
